#   _____ _           _   ______        _ _
#  / ____| |         | | |  ____|      | (_)
# | |    | |__   __ _| |_| |__ ___  ___| |_ _ __   __ _ ___
# | |    | '_ \ / _` | __|  __/ _ \/ _ \ | | '_ \ / _` / __|
# | |____| | | | (_| | |_| | |  __/  __/ | | | | | (_| \__ \
#  \_____|_| |_|\__,_|\__|_|  \___|\___|_|_|_| |_|\__, |___/
#                                                  __/ |
#                                                 |___/
#          ___     _              _        _
#          | _ \___| |___  __ _ __| |___ __| |
#          |   / -_) / _ \/ _` / _` / -_) _` |
#          |_|_\___|_\___/\__,_\__,_\___\__,_|


# This is used when an update modifies the config. If checks this value and
#warns you when the config file does not match the version needed. This number
# may be changed when the correct additions to the config are made.
ConfigVersion: 5


#------------------------------------------------------------------------
# Settings
#------------------------------------------------------------------------

#When true, actions will be announced to everyone on the server.
AnnounceActionsGlobally: false


#------------------------------------------------------------------------
# Theme
#------------------------------------------------------------------------

# These allow you to modify the colors of the plugin, each are named by
# what they are by default

# Modifies the dividing lines: "---------------------"
Grey: "&8&l"

# Modifies the help page headers: "Actions" and "Feelings"
GoldOne: "&6&l"

# Modifies the command colors of the bottom of the help pages: "/actions 1"
GoldTwo: "&6"

# Modifies the page number at the top of the help pages: "[1/7]"
Yellow:  "&e"

# Modifies the bottom of the help pages: "Do [command] for the next page."
LightGrey: "&7"